//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebExtensionApi.BlogCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public Blog()
        {
            this.BlogComments = new HashSet<BlogComment>();
            this.BlogImages = new HashSet<BlogImage>();
        }
    
        public int ID { get; set; }
        public string Text { get; set; }
        public int Rating { get; set; }
        public int CategoryID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<BlogComment> BlogComments { get; set; }
        public virtual ICollection<BlogImage> BlogImages { get; set; }
        public virtual Category Category { get; set; }
    }
}
