//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebExtensionApi.BlogCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogImage
    {
        public int ID { get; set; }
        public string ImageURL { get; set; }
        public int BlogID { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
